common/national_focus/FA_hungary.txt

thanks for fucking with the github fullchord, dante fix so this shit can get fixed

mutual exclusive fix

---

events/Germany.txt

Fixed event firing every month
fixed application to correct mio

Wehermacht Expansion Event Fix

---

common/country_leader/01_traits.txt
common/game_rules/00_game_rules.txt
common/national_focus/germany.txt
history/countries/FIN - Finland.txt

Finland Vanilla
Germany Vanilla Cap added back

Sigma stuff

---

common/national_focus/germany.txt
common/units/equipment/upgrades/land_upgrades.txt

Rubber Refinery Affected by Focuses in Germany Eco Tree
Tungsten Focus added to Swedish

Germany Rubber Refinery Rubber Add on Focus and Tungsten Focus

---

common/national_focus/finland.txt

Added back Long Range Patrol Companies
Army Generals don't get deleted when during civil war

Finland Fix

---

common/ideas/mass_media.txt

5% weekly stability and War support. Seems like a typo.

Press Law LOL

---

common/characters/CUB.txt
common/decisions/formNation.txt
common/defines/LS_defines.lua
common/national_focus/Cuba.txt

Jg please push

---

common/national_focus/usa.txt
events/USA.txt
localisation/english/mtg_focus_l_english.yml

Makes the civil war easier
Adds cool new design

Silver Lesion Fix

---

common/decisions/ROM.txt
common/decisions/categories/ROM_decision_categories.txt

TCDTF Rom Fix

---

common/characters/NZL.txt
common/decisions/formNation.txt
common/ideas/new_zealand.txt
common/ideas/south_africa.txt
common/military_industrial_organization/organizations/NZL_organization.txt
common/national_focus/Cuba.txt
common/national_focus/new_zealand.txt
common/national_focus/r56_south_africa.txt
localisation/english/NZL_l_english.yml
localisation/english/SAF_l_english.yml

Common wealth touching 

---

common/decisions/_generic_decisions.txt
common/national_focus/belgium.txt
common/national_focus/congo.txt
common/national_focus/germany.txt
common/national_focus/japan.txt
common/national_focus/toa_shared_military_branch.txt

Makes it so every major gets 1 extra specialization and that's it

Special Forces Branches Nerf

---

common/ideas/_economic.txt
common/ideas/britain.txt

Touched Trade law for Fascist
Buffed change in course pp

TCDTF UK Alt Hist

---

common/decisions/ENG.txt
common/decisions/categories/ENG_decision_categories.txt
events/PoliticalEvents.txt

TCDTF Commie UK

---

common/ideas/_economic.txt
common/national_focus/germany.txt
localisation/english/countries_l_english.yml

-Eco laws are now Vanilla
- Germany Autarky focus requires less oil to take

TCDTF Eco Laws

---

common/national_focus/portugal.txt

- Adds the embargo back to the fifth empire
- Now gives them bonuses to steel mills and aluminum mills
- Gives them closed economy

TCDTF Portugal Jud Fix

---

common/country_leader/00_traits.txt
common/ideas/SOV.txt
common/national_focus/soviet.txt

Major Attack Factor  15% -> 5% attack factor
Focus Times Increased to Represent Importance of Focus
Mutually Exclusive Fix
etc

Beaten but Not Defeated Nerf

---

common/decisions/USA.txt
common/ideas/_economic.txt
common/national_focus/usa.txt

Fix Decision For Total mob
Slightly Increase Focus Days for War Eco
If you don't have Phillapeans you will not gain pp from focus where you release it

Nerf Communist Path

---

common/dynamic_modifiers/special_forces_over_50_cap.txt
common/ideas/special_forces_over_50_cap.txt
common/on_actions/00_on_actions.txt
common/scripted_triggers/special_forces_limit.txt
events/special_forces_cap_event.txt
localisation/english/ZIM_l_english.yml

Special forces fix

---

common/decisions/SPR.txt

Fixes unplanned offensive. Was referencing dynamic modifier and not a state modifier.

TCDTF Unplanned Offensive FIX

---

common/ideas/bulgaria.txt
common/national_focus/bulgaria.txt

Easier faction managment and added a focus to eco tree

Alt hist Bulgaria updated

---

common/decisions/SPR.txt
common/ideas/r56_spain_republic.txt
common/ideas/spain_nationalist.txt
common/national_focus/spain.txt

Tech researches at the end of the tree now have ahead reduction All paths get an intel agency
All paths get more pp
Decisions are cheaper

TCDTF Spain Buff

---

common/characters/BEL.txt
common/ideas/belgium.txt
common/national_focus/belgium.txt
common/national_focus/congo_shared.txt

- Colonial joint focus tree is shorter
- Political tree shorter
- Army tree shorter

TCDTF Belgium

---

common/decisions/formNation.txt
common/national_focus/uk.txt

- Removed British Isles formable from decisions
- Adds cores to the consolidate the british isles focus.

TCDTF United British Isles

---

interface/countrylogisticsview.gui

- Removes the ability to delete stockpiles
- Fuck Cheaters

TCDTF Stockpile

---

common/country_leader/00_traits.txt

better traits

---

common/defines/LS_defines.lua

TCDTF Strats Fix

---

common/decisions/MEX.txt
common/national_focus/mexico.txt

- 100 day focus for a research slot lol
- Doesn't start with MIO unlocked so gave sizes to MIO through focus

TCDTF Mexico

---

common/characters/ENG.txt
common/ideas/britain.txt
common/ideas/finances.txt
common/ideas/japan.txt
common/ideas/mexico_mtg_placeholder.txt
common/military_industrial_organization/organizations/MEX_organization.txt
common/national_focus/mexico.txt
common/national_focus/r56_sweden.txt
common/national_focus/spain.txt
common/national_focus/uk.txt
common/technologies/MTG_naval_Support.txt
common/units/equipment/modules/00_ship_modules.txt
common/units/equipment/ship_hull_submarine.txt

- England fascist advisor bugged
- England more escort efficiency and sub detection
- Civilian spendings nerf
- Army financing nerf
- Foreign subsidies nerf
- Commie Japan navy nerf
- Mexico has MIOS now
- Mexico no longer perma debuffed
- 56 Sweden Nonaligned and Communist can flip faster
- Spain get focus to give guns
- Fascist UK can flip faster
- Naval invasion tech is 1 day
- Snorkels nerfed
- Submarine hulls ic increased

TCDTF Changes

---

common/technologies/MTG_naval.txt
common/technologies/NSB_armor.txt
common/technologies/artillery.txt
common/technologies/bba_air_techs.txt
common/technologies/electronic_mechanical_engineering.txt
common/technologies/industry.txt
common/technologies/infantry.txt
common/technologies/naval.txt
common/technologies/r56_vechicles.txt
common/technologies/support.txt
interface/countrytechtreeview.gui
localisation/english/replace/tank_modules_l_english.yml

TCDTF Tech

---

common/decisions/BEL_HOL_decisions.txt
common/decisions/categories/BEL_HOL_decision_categories.txt
localisation/english/HOL_l_english.yml

- Gives up colonies for factories

TCDTF Giving Up Colonies Decisions

---

common/decisions/_generic_decisions.txt

comments out the decision to object to an attache

Removes AI objecting to attaches

---

common/characters/CAN.txt
history/countries/CAN - Canada.txt
history/states/331-Newfoundland.txt
history/states/465-New Brunswick.txt
history/states/466-Quebec.txt
history/states/468-Nunavut.txt
history/states/730-St Pierre and Miquelon .txt
history/states/860-Cote-Nord.txt
history/states/861-Saguenay.txt
history/states/862-ouest du quebec.txt
history/states/863-Maurice.txt

Quebec Removal Cores

---

history/states/1053-Saarland.txt
history/states/42-Rhineland.txt
history/states/50-Baden.txt
history/states/51-Moselland.txt
history/states/52-Wuttemberg.txt
history/states/53-Oberbayern.txt
history/states/54-Bayreuth.txt
history/states/56-Weser-Ems.txt
history/states/58-Schleswig - Holstein.txt
history/states/59-Ost - Hannover.txt
history/states/61-Mecklenburg.txt
history/states/63-WestPrussen.txt
history/states/65-Sachsen.txt
history/states/66-Niederschlesien.txt
history/states/67-Oberschlesien.txt
history/states/762-Katowice.txt
history/states/807-Gdynia.txt
history/states/86-Poznan.txt
history/states/922-Frankfurt.txt
history/states/923-Baden.txt
history/states/964-Northern Schleswig.txt
history/states/989-Ostrhineland.txt
history/states/998-Southern Schleswig.txt

Germany REleaseables now

---

history/states/115-Sicily.txt
history/states/117-Napoli.txt
history/states/156-Calabria.txt
history/states/157-Abruzzo.txt
history/states/849-Puglia.txt

Remove Italian Releaseables
